Controllers/CartController.cs
using E_commerce.Models;
using E_commerce_MVC.Repository;
using E_commerce_MVC.Utility;
using E_commerce_MVC.viewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_commerce_MVC.Controllers
{
    // Added by MAi
    public class CartController : Controller
    {

        private readonly ICartRepository _cartRepositry;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IProductRepository _productRepository;

        public CartController(ICartRepository cartRepositry, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IProductRepository productRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _productRepository = productRepository;
            _cartRepositry = cartRepositry;
        }

        public IActionResult Index()
        {
            var checkIfUserSignedInOrNot = _signInManager.IsSignedIn(User);
            if (checkIfUserSignedInOrNot)
            {
                var userId = _userManager.GetUserId(User);

                IEnumerable<Cart> CartList = _cartRepositry.GetProductsInCart(userId);

                CartIndexViewModel CartViewModel = new CartIndexViewModel();
                foreach (var item in CartList)
                {
                    Cart cart = _cartRepositry.Get(p => p.Product_Id == item.Product_Id);
                    CartViewModel.ProductName.Add(cart.product.Name);
                    CartViewModel.ProductId.Add(cart.product.Id);
                    CartViewModel.ImgUrl.Add(cart.product.Image_Url);
                    CartViewModel.Quantity.Add(cart.Quantity);
                    CartViewModel.Price.Add(cart.product.Price);
                    CartViewModel.Total.Add(cart.product.Price * cart.Quantity);
                }
                var currentUser = _userManager.GetUserAsync(User);
                string username = User.Identity.Name;
                ViewData["Username"] = username;

                return View("CartIndex", CartViewModel);
            }

            return RedirectToAction("login", "Account");

        }

        [Authorize]
        public async Task<IActionResult> AddToCart(int productId)
        {
            var productAddToCart = _productRepository.Get(p => p.Id == productId);
            var checkIfUserSignedInOrNot = _signInManager.IsSignedIn(User);
            if (checkIfUserSignedInOrNot)
            {
                // User Signed in
                // Get User Id
                var user = _userManager.GetUserId(User);
                if (user != null)
                {
                    // check if the signed user has any cart or not
                    var getTheCartIfAnyExistForTheUser = _cartRepositry.CountCartForUser(user);
                    if (getTheCartIfAnyExistForTheUser.Count() > 0)
                    {
                        // check if the item is already in the cart or not
                        var getTheQuantity = _cartRepositry.CheckIfTheProductExists(productId, user);
                        if (getTheQuantity != null)
                        {
                            // if the item is already in the cart just increase the quantity by 1 and update the cart
                            getTheQuantity.Quantity = getTheQuantity.Quantity + 1;
                            _cartRepositry.update(getTheQuantity);
                        }
                        else
                        {
                            // user has a cart but adding a new item to the existing cart
                            Cart newItemToCart = new Cart
                            {
                                Product_Id = productId,
                                Customer_Id = user,
                                Quantity = 1
                            };
                            _cartRepositry.insert(newItemToCart);
                        }
                    }
                    else
                    {
                        // user has no cart. Adding a new cart for the user
                        Cart newItemToCart = new Cart
                        {
                            Product_Id = productId,
                            Customer_Id = user,
                            Quantity = 1
                        };
                        _cartRepositry.insert(newItemToCart);
                    }
                    _cartRepositry.save();

                    // Count Items in Cart
                    var count = _cartRepositry.CountItems(user);
                    HttpContext.Session.SetInt32(CartCount.sessionCount, count);
                }
            }
            return RedirectToAction("GetAllproducts", "product");
        }

        public ActionResult Remove(int id)
        {
            Cart cartItem = _cartRepositry.Get(p => p.Product_Id == id); // Get the item to delete
            if (cartItem != null)
            {

                // If quantity is 1 or less, remove the item from the cart
                _cartRepositry.Remove(id);
                _cartRepositry.save(); // Save changes

                // Count Items in Cart
                var user = _userManager.GetUserId(User);
                var count = _cartRepositry.CountItems(user);
                HttpContext.Session.SetInt32(CartCount.sessionCount, count);
            }

            return RedirectToAction("Index", new { id = cartItem?.Customer_Id });
        }

        public ActionResult DecreaseQuantity(int id)
        {
            Cart cartItem = _cartRepositry.Get(p => p.Product_Id == id); // Get the item to delete

            if (cartItem != null)
            {
                if (cartItem.Quantity > 1)
                {
                    // Decrease quantity by 1
                    cartItem.Quantity--;
                    _cartRepositry.update(cartItem); // Update the quantity in the repository
                    _cartRepositry.save(); // Save changes
                }
                else
                {
                    // If quantity is 1 or less, remove the item from the cart
                    _cartRepositry.Remove(id);
                    _cartRepositry.save(); // Save changes
                }
            }

            var user = _userManager.GetUserId(User);
            var count = _cartRepositry.CountItems(user);
            HttpContext.Session.SetInt32(CartCount.sessionCount, count);

            return RedirectToAction("Index", new { id = cartItem?.Customer_Id });
        }


        public ActionResult IncreaseQuantity(int id)
        {
            Cart cartItem = _cartRepositry.Get(p => p.Product_Id == id); // Get the item to delete

            if (cartItem != null)
            {
                // Increase quantity by 1
                cartItem.Quantity++;
                _cartRepositry.update(cartItem); // Update the quantity in the repository
                _cartRepositry.save(); // Save changes
            }

            var user = _userManager.GetUserId(User);
            var count = _cartRepositry.CountItems(user);
            HttpContext.Session.SetInt32(CartCount.sessionCount, count);

            return RedirectToAction("Index", new { id = cartItem?.Customer_Id });
        }
        public IActionResult AddToCartFromWishList(int productId)
        {
            var productAddToCart = _productRepository.Get(p => p.Id == productId);
            var checkIfUserSignedInOrNot = _signInManager.IsSignedIn(User);
            if (checkIfUserSignedInOrNot)
            {
                // User Signed in
                // Get User Id
                var user = _userManager.GetUserId(User);
                if (user != null)
                {
                    // check if the signed user has any cart or not
                    var getTheCartIfAnyExistForTheUser = _cartRepositry.CountCartForUser(user);
                    if (getTheCartIfAnyExistForTheUser.Count() > 0)
                    {
                        // check if the item is already in the cart or not
                        var getTheQuantity = _cartRepositry.CheckIfTheProductExists(productId, user);
                        if (getTheQuantity != null)
                        {
                            // if the item is already in the cart just increase the quantity by 1 and update the cart
                            getTheQuantity.Quantity = getTheQuantity.Quantity + 1;
                            _cartRepositry.update(getTheQuantity);
                        }
                        else
                        {
                            Cart newItemToCart = new Cart
                            {
                                Product_Id = productId,
                                Customer_Id = user,
                                Quantity = 1
                            };
                            _cartRepositry.insert(newItemToCart);
                        }
                    }
                    else
                    {
                        Cart newItemToCart = new Cart
                        {
                            Product_Id = productId,
                            Customer_Id = user,
                            Quantity = 1
                        };
                        _cartRepositry.insert(newItemToCart);
                    }
                    _cartRepositry.save();
                    var count = _cartRepositry.CountItems(user);
                    HttpContext.Session.SetInt32(CartCount.sessionCount, count);
                }
            }
            return Json(new { success = true });
        }

    }
}

Controllers/CategoryController.cs
using E_commerce.Models;
using E_commerce_MVC.Repository;
using E_commerce_MVC.Utility;
using E_commerce_MVC.viewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace E_commerce_MVC.Controllers
{

    //[Route("Home")]
    public class CategoryController : Controller
    {

        private readonly IProductRepository ProductRepository;
        private readonly ICategoryRepository CategoryRepository;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly Context _context;

        public CategoryController(Context context,IProductRepository ProductRepository, ICategoryRepository CategoryRepository,IWebHostEnvironment webHostEnvironment, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.ProductRepository = ProductRepository;
            this.CategoryRepository = CategoryRepository;
            this.webHostEnvironment = webHostEnvironment;
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        public IActionResult GetAllCategory()
        {
            // Added by MAi
            var claim = _signInManager.IsSignedIn(User);
            if (claim)
            {
                // if the user signed in
                var userId = _userManager.GetUserId(User);
                var count = _context.Carts.Where(u => u.Customer_Id.Contains(userId) && !u.IsDeleted).Count();

                HttpContext.Session.SetInt32(CartCount.sessionCount, count);
            }
            List<Category> categories = (List<Category>)CategoryRepository.GetAllCategories();
            List<Product> latestProductsInCategories = (List<Product>)ProductRepository.GetLatestProduct();
            ListOfProductAndListOfCategory ListOfProductAndListOfCategory = new ListOfProductAndListOfCategory();
            ListOfProductAndListOfCategory.categories = categories;
            ListOfProductAndListOfCategory.products = latestProductsInCategories;
            return View("GetAllCategory", ListOfProductAndListOfCategory);
        }


        public IActionResult addNewCategory()
        {

            return View();

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult addNewCategory(NewcategoryVM newcategory)
        {
            if (ModelState.IsValid)
            {
                string UploadPath = Path.Combine(webHostEnvironment.WebRootPath, "img/gallery");
                string imageName = Guid.NewGuid().ToString() + "-" + newcategory.imageURL.FileName;
                string filePath = Path.Combine(UploadPath, imageName);

                using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                {
                    newcategory.imageURL.CopyTo(fileStream);
                }

                Category category = new Category();
                category.Name = newcategory.Name;
                category.imageURL = imageName;

                CategoryRepository.insert(category);
                CategoryRepository.save();

        
                return RedirectToAction("GetAllCategory");
            }

       
            return View(newcategory);
        }
    }
}

Views/Shared/_FastFreeDelivery.cshtml
<div class="categories-area section-padding40 gray-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-cat mb-50 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".2s">
                    <div class="cat-icon">
                        <img src="/img/icon/services1.svg" alt="">
                    </div>
                    <div class="cat-cap">
                        <h5>Fast & Free Delivery</h5>
                        <p>Free delivery on all orders</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-cat mb-50 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".2s">
                    <div class="cat-icon">
                        <img src="/img/icon/services2.svg" alt="">
                    </div>
                    <div class="cat-cap">
                        <h5>Fast & Free Delivery</h5>
                        <p>Free delivery on all orders</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-cat mb-30 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s">
                    <div class="cat-icon">
                        <img src="/img/icon/services3.svg" alt="">
                    </div>
                    <div class="cat-cap">
                        <h5>Fast & Free Delivery</h5>
                        <p>Free delivery on all orders</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-cat wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">
                    <div class="cat-icon">
                        <img src="/img/icon/services4.svg" alt="">
                    </div>
                    <div class="cat-cap">
                        <h5>Fast & Free Delivery</h5>
                        <p>Free delivery on all orders</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using System.Security.Claims
﻿@using E_commerce.Models;
@using E_commerce_MVC.Repository;
@using E_commerce_MVC.Utility;
@using E_commerce_MVC.viewModels;
@using Microsoft.AspNetCore.Authorization;
@using Microsoft.AspNetCore.Identity;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.EntityFrameworkCore;
@inject IHttpContextAccessor HttpContextAccessor

<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Fashion | Teamplate</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/slicknav.css">
    <link rel="stylesheet" href="/css/flaticon.css">
    <link rel="stylesheet" href="/css/progressbar_barfiller.css">
    <link rel="stylesheet" href="/css/gijgo.css">
    <link rel="stylesheet" href="/css/animate.min.css">
    <link rel="stylesheet" href="/css/animated-headline.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <link rel="stylesheet" href="/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/css/themify-icons.css">
    <link rel="stylesheet" href="/css/slick.css">
    <link rel="stylesheet" href="/css/nice-select.css">
    <link rel="stylesheet" href="/css/style.css">

</head>
<body style="width:100%">
    @* class="full-wrapper" *@
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="/img/logo/loder.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->
    <header>

        <!-- Header Start -->
        <div class="header-area ">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="menu-wrapper d-flex align-items-center justify-content-between">
                        <div class="header-left d-flex align-items-center">
                            <!-- Logo -->
                            <div class="logo">
                                <a asp-action="getallcategory" asp-controller="category"><img src="/img/logo/logo.png" alt=""></a>
                            </div>
                            <!-- Main-menu -->
                            <partial name="_NavPartial" />
                            <div class="header-right1 d-flex align-items-center">
                                <!-- Social -->
                                <div class="header-social d-none d-md-block">
                                    @{
                                        var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                                    }

                                    @if (User.Identity.IsAuthenticated == true)


                                    {
                                        <a href="@Url.Action("Index", "WishList", new { id = id })" title="Wishlist">
                                            <i class="fa fa-heart"></i>
                                        </a>
                                    }
                                </div>

                                <!-- Search Box -->
                                <div class="search d-none d-md-block">
                                    <ul class="d-flex align-items-center">
                                        <li class="mr-15">
                                            <div class="nav-search search-switch">
                                                <i class="ti-search"></i>
                                            </div>
                                        </li>
                                        <li>
                                            @if (HttpContextAccessor.HttpContext.Session.GetInt32(CartCount.sessionCount) != null)
                                            {
                                                var count = HttpContextAccessor.HttpContext.Session.GetInt32(CartCount.sessionCount);
                                            <li class="nav-item">
                                                <a asp-controller="Cart" asp-action="Index" class="nav-link">
                                                    <div class="card-stor">
                                                        <img src="/img/gallery/card.svg" alt="">
                                                        <span>(@count)</span>
                                                    </div>
                                                </a>
                                            </li>
                                            }
                                            else
                                            {
                                            <li>
                                                  <a asp-controller="Cart" asp-action="Index" class="nav-link">
                                                <div class="card-stor">
                                                    <img src="/img/gallery/card.svg" alt="">
                                                    <span>0</span>
                                                </div>
                                                </a>
                                            </li>
                                          
                                            }
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Header End -->
    </header>
    <!-- header end -->
    @RenderBody()


    <!-- JS here -->
    <!-- Jquery, Popper, Bootstrap -->
    <script src="/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="/js/popper.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <!-- Slick-slider , Owl-Carousel ,slick-nav -->
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/slick.min.js"></script>
    <script src="/js/jquery.slicknav.min.js"></script>

    <!-- One Page, Animated-HeadLin, Date Picker -->
    <script src="/js/wow.min.js"></script>
    <script src="/js/animated.headline.js"></script>
    <script src="/js/jquery.magnific-popup.js"></script>
    <script src="/js/gijgo.min.js"></script>

    <!-- Nice-select, sticky,Progress 
    <script src="/js/jquery.nice-select.min.js"></script>
    <script src="/js/jquery.sticky.js"></script>
    <script src="/js/jquery.barfiller.js"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="/js/jquery.counterup.min.js"></script>
    <script src="/js/waypoints.min.js"></script>
    <script src="/js/jquery.countdown.min.js"></script>
    <script src="/js/hover-direction-snake.min.js"></script>

    <!-- contact js -->
    <script src="/js/contact.js"></script>
    <script src="/js/jquery.form.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/mail-script.js"></script>
    <script src="/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="/js/plugins.js"></script>
    <script src="/js/main.js"></script>

    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: false)
    }



</body>
</html>

Views/Shared/_NavPartial.cshtml
<div class="main-menu  d-none d-lg-block">
    <nav>
        <ul id="navigation">
            @if (!User.Identity.IsAuthenticated)
            {

                <li><a href="/Account/login">Login</a></li>

                <li><a href="/Account/Register">Register</a></li>
            }
            @if (User.Identity.IsAuthenticated == true)

            {

                <li><a asp-action="getallcategory" asp-controller="category">Home</a></li>
                <li><a asp-action="GetAllProducts" asp-controller="Product">shop</a></li>
               
                @if (User.IsInRole("Admin") == true)
                {
                    <li><a href="/Account/RegisteredCustomers">Registered</a></li>
                    <li><a asp-action="addnewproduct" asp-controller="Product">Add Product</a></li>
                    <li><a asp-action="addnewcategory" asp-controller="Category">Add Category</a></li>
                }
                <li><a href="/Account/signout">log out</a></li>
                @* <li><a href="/product/GetAllproducts">All Products</a></li> *@
                <li>
                    <a href="#">Details</a>
                    <ul class="submenu">
                        <li><a href="/shipment/index">Shipment Details</a></li>
                        <li><a href="/payment/index">Payment Details</a></li>
                       


                </li>



            }
        </ul>
    </nav>
</div>
                        </div>

Views/Shared/_footer.cshtml
<footer>
    <!-- Footer Start-->
    <div class="footer-area footer-padding">
        <div class="container-fluid ">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-8 col-sm-8">
                    <div class="single-footer-caption mb-50">
                        <div class="single-footer-caption mb-30">
                            <!-- logo -->
                            <div class="footer-logo mb-35">
                                <a href="index.html"><img src="/img/logo/logo2_footer.png" alt=""></a>
                            </div>
                            <div class="footer-tittle">
                                <div class="footer-pera">
                                    <p>Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.</p>
                                </div>
                            </div>
                            <!-- social -->
                            <div class="footer-social">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-pinterest-p"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Quick links</h4>
                            <ul>
                                <li><a href="#">Image Licensin</a></li>
                                <li><a href="#">Style Guide</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Shop Category</h4>
                            <ul>
                                <li><a href="#">Image Licensin</a></li>
                                <li><a href="#">Style Guide</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Pertners</h4>
                            <ul>
                                <li><a href="#">Image Licensin</a></li>
                                <li><a href="#">Style Guide</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- footer-bottom area -->
    <div class="footer-bottom-area">
        <div class="container">
            <div class="footer-border">
                <div class="row d-flex align-items-center">
                    <div class="col-xl-12 ">
                        <div class="footer-copy-right text-center">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>
<!--? Search model Begin -->
<div class="search-model-box">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-btn">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Searching key.....">
        </form>
    </div>
</div>
<!-- Search model end -->
<!-- Scroll Up -->
<div id="back-top">
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>