Models/Shipment.cs
using E_commerce_MVC.interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_commerce.Models
{
    public class Shipment:ISoftDeletable
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip_Code { get; set; }
        public bool IsDeleted { get; set; } = false;
        [ForeignKey("customer")]
        public string Customer_Id { get; set; }
        public ApplicationUser customer { get; set; }
        public ICollection<Order>? orders { get; set; }

    }
}

Controllers/ShipmentController.cs
using E_commerce.Models;
using E_commerce.Repository;
using E_commerce_MVC.viewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace E_commerce_MVC.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly IRepository<Shipment> repository;
        private readonly UserManager<ApplicationUser> userManager;

        public ShipmentController(IRepository<Shipment> repository, UserManager<ApplicationUser> userManager)
        {
            this.repository = repository;
            this.userManager = userManager;
        }


        //for admin ya reem
        // [Authorize(Roles = "admin")]
        public IActionResult Index(int page = 1, int pageSize = 5)
        {
            var shipments = repository.GetAll();
            var users = userManager.Users.ToList();
            ViewData["Users"] = users;

            var paginatedShipments = shipments.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewData["CurrentPage"] = page;
            ViewData["TotalPages"] = (shipments.Count + pageSize - 1) / pageSize;

            return View(paginatedShipments);
        }

        [HttpGet]
        //[Authorize]
        public async Task<IActionResult> AddShipment()
        {
            var currentUser = await userManager.GetUserAsync(User);
            string email = currentUser.Email;
            ViewData["Email"] = email;
            string username = User.Identity.Name;
            ViewData["Username"] = username;
            return View("AddShipment");
        }


        [HttpPost]
        public IActionResult AddShipment(ShipmentViewModel shipmentViewModel)
        {
            if (ModelState.IsValid)
            {
                Shipment shipment = new()
                {
                    Date = shipmentViewModel.Date,
                    Address = shipmentViewModel.Address,
                    City = shipmentViewModel.City,
                    State = shipmentViewModel.State,
                    Country = shipmentViewModel.Country,
                    Zip_Code = shipmentViewModel.Zip_Code,
                    Customer_Id = User.FindFirstValue(ClaimTypes.NameIdentifier)

                };
                repository.insert(shipment);
                repository.save();
                //return Content("Done");
                return RedirectToAction("AddPayment", "Payment");
            }
            return View("AddShipment");
        }
    }
}

Views/Shipment/AddShipment.cshtml
@model E_commerce_MVC.viewModels.ShipmentViewModel

@{
    ViewData["Title"] = "AddShipment";
}
    
 <style>
    body {
        background-color: #f8f9fa;
        font-family: Arial, sans-serif;
    }
       
    .card {
        border-radius: 15px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .card-header {
        background-color: #9F78FF;
        color: #fff;
        border-radius: 15px 15px 0 0;
    }
    .card-body {
        padding: 20px;
    }

    .btn {
        background-color: #9F78FF;
        border-color: #9F78FF;
        color: #fff;
    }

    .btn:hover {
        background-color: #9F78FF;
        border-color: #9F78FF;
        color: #fff;
    }

    .shipment-image {
        width: 100%; 
        height: auto; 
            
    }

    .big-label {
        font-size: 18px;
    }

    .custom-input {
        height: 40px;        
        padding: 10px;
    }
</style> 

<div class="container" style="margin-bottom: 150px;">
    <h1>Shipping details</h1>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 style="display:inline; color:#fff">Welcome, @ViewData["Username"] ! </h1>
                    <p style="display:inline; float: right; color:#fff">@ViewData["Email"]</p>
                </div>

                <div class="card-body">
                    <form asp-action="AddShipment">
                        <div class="form-row">
                            <div class="col-md-12">
                            <label asp-for="Date" class="form-label big-label">Date <span class="text-danger">*</span></label>
                                <input asp-for="Date" class="form-control custom-input form-control-lg big-label" />
                            <span asp-validation-for="Date" class="text-danger"></span>
                                <br />
                        </div>
                      
                            <div class="col-md-12">
                            <label asp-for="Address" class="form-label big-label">Address <span class="text-danger">*</span></label>
                                <input asp-for="Address" class="form-control custom-input big-label" placeholder="Address" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                                <br />
                        </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-8 mb-3">
                                <label asp-for="City" class="form-label big-label">City <span class="text-danger">*</span></label>
                                <input asp-for="City" class="form-control custom-input form-control-lg big-label" placeholder="City" />
                                <span asp-validation-for="City" class="text-danger"></span>
                                <br />
                            </div>

                            <div class="col-md-4">
                                <label asp-for="State" class="form-label big-label">State <span class="text-danger">*</span></label>
                                <select asp-for="State" class="form-select  big-label">
                                    <option selected>Choose...</option> 
                                    <option value="California">California</option>
                                    <option value="Texas">Texas</option>
                                    <option value="New York">New York</option>
                                </select>
                                <span asp-validation-for="State" class="text-danger"></span>
                                <br />
                            </div>
                        </div>

                        <div class="form-row">


                            <div class="form-group col-md-8">
                            <label asp-for="Country" class="form-label big-label">Country <span class="text-danger">*</span></label>
                                <input asp-for="Country" class="form-control custom-input form-control-lg big-label" placeholder="Country" />
                            <span asp-validation-for="Country" class="text-danger"></span>
                                <br />
                        </div>

                            <div class="form-group col-md-4">
                            <label asp-for="Zip_Code" class="form-label big-label">Zip Code <span class="text-danger">*</span></label>
                                <input asp-for="Zip_Code" class="form-control custom-input form-control-lg big-label" placeholder="Zip Code" />
                            <span asp-validation-for="Zip_Code" class="text-danger"></span>
                                <br />
                        </div>
                        </div>

                        <button type="submit" class="btn btn-primary btn-block">Create</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <img src="/img/gallery/shipment.png" class="img-fluid" alt="Shipment Image">
        </div>
    </div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.min.js" integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

@await Html.PartialAsync("_footer");

Views/Shipment/Index.cshtml
@model List<Shipment>

@{
   
    var users = ViewData["Users"] as List<ApplicationUser>;
    var currentPage = (int)ViewData["CurrentPage"];
    var totalPages = (int)ViewData["TotalPages"];

}

<style>
    .page-item.active .page-link{
        z-index: 1;
        color: #fff;
        background-color: #9F78FF;
        border-color: #9F78FF;
    }

    .page-link{
        color: #9F78FF;
    }
        
</style>



<div class="container" style="margin-bottom: 150px;">
    <table class="table table-hover table-bordered  table table-striped">
        <thead class="dark-green">
            <tr>
               
                <th scope="col">Shipment Id</th>
                <th scope="col">Customer Id</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Date</th>
                <th scope="col">Address</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">Country</th>
                <th scope="col">Zip_Code</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Shipment item in Model)
            {
                <tr>
                   
                    <td>@item.Id</td>
                    <td>@item.Customer_Id</td>
                    <td>@item.customer.UserName</td>
                    @* <td>@users?.FirstOrDefault(u => u.Id == item.Customer_Id)?.UserName</td> *@
                    <td>@item.customer.NormalizedEmail</td>
                    <td>@item.Date</td>
                    <td>@item.Address</td>
                    <td>@item.City</td>
                    <td>@item.State</td>
                    <td>@item.Country</td>
                    <td>@item.Zip_Code</td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div class="d-flex justify-content-center" >
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @for (int i = 1; i <= totalPages; i++)
            {
                <li class="page-item @(i == currentPage ? "active" : "")">
                    <a style="padding:12px" class="page-link " href="@Url.Action("Index", "Shipment", new { page = i }) ">@i</a>
                </li>
            }
        </ul>
    </nav>
</div>
<br />
<br />
@await Html.PartialAsync("_footer");